name: Tests CI

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

      - name: Build and start containers
        run: |
          docker compose up --build -d

      - name: Wait for API to be healthy
        run: |
          echo "Waiting for API to become healthy..."
          for i in {1..10}; do
            if docker compose exec api curl -sf http://localhost:8000; then
              echo "API is up!"
              exit 0
            fi
            echo "API not ready yet (attempt $i)..."
            sleep 5
          done
          echo "API did not become healthy in time. Failing."
          exit 1

      - name: Run tests inside the container
        run: |
          docker compose exec api pytest
